import { Schema, model } from "mongoose";

const CURRENCY_CODES = [
  // "AED",
  // "AFN",
  // "ALL",
  // "AMD",
  // "ANG",
  // "AOA",
  // "ARS",
  // "AUD",
  // "AWG",
  // "AZN",
  // "BAM",
  // "BBD",
  // "BDT",
  // "BGN",
  // "BHD",
  // "BIF",
  // "BMD",
  // "BND",
  // "BOB",
  // "BOV",
  // "BRL",
  // "BSD",
  // "BTN",
  // "BWP",
  // "BYN",
  // "BZD",
  // "CAD",
  // "CDF",
  // "CHE",
  // "CHF",
  // "CHW",
  // "CLF",
  // "CLP",
  // "CNY",
  // "COP",
  // "COU",
  // "CRC",
  // "CUC",
  // "CUP",
  // "CVE",
  // "CZK",
  // "DJF",
  // "DKK",
  // "DOP",
  // "DZD",
  // "EGP",
  // "ERN",
  // "ETB",
  // "EUR",
  // "FJD",
  // "FKP",
  // "GBP",
  // "GEL",
  // "GHS",
  // "GIP",
  // "GMD",
  // "GNF",
  // "GTQ",
  // "GYD",
  "HKD",
  // "HNL",
  // "HRK",
  // "HTG",
  // "HUF",
  // "IDR",
  // "ILS",
  // "INR",
  // "IQD",
  // "IRR",
  // "ISK",
  // "JMD",
  // "JOD",
  // "JPY",
  // "KES",
  // "KGS",
  // "KHR",
  // "KMF",
  // "KPW",
  // "KRW",
  // "KWD",
  // "KYD",
  // "KZT",
  // "LAK",
  // "LBP",
  // "LKR",
  // "LRD",
  // "LSL",
  // "LYD",
  // "MAD",
  // "MDL",
  // "MGA",
  // "MKD",
  // "MMK",
  // "MNT",
  // "MOP",
  // "MRU",
  // "MUR",
  // "MVR",
  // "MWK",
  // "MXN",
  // "MXV",
  // "MYR",
  // "MZN",
  // "NAD",
  // "NGN",
  // "NIO",
  // "NOK",
  // "NPR",
  // "NZD",
  // "OMR",
  // "PAB",
  // "PEN",
  // "PGK",
  // "PHP",
  // "PKR",
  // "PLN",
  // "PYG",
  // "QAR",
  // "RON",
  // "RSD",
  // "RUB",
  // "RWF",
  // "SAR",
  // "SBD",
  // "SCR",
  // "SDG",
  // "SEK",
  // "SGD",
  // "SHP",
  // "SLE",
  // "SOS",
  // "SRD",
  // "SSP",
  // "STN",
  // "SVC",
  // "SYP",
  // "SZL",
  // "THB",
  // "TJS",
  // "TMT",
  // "TND",
  // "TOP",
  // "TRY",
  // "TTD",
  // "TWD",
  // "TZS",
  // "UAH",
  // "UGX",
  // "USD",
  // "USN",
  // "UYI",
  // "UYU",
  // "UZS",
  // "VED",
  // "VEF",
  // "VND",
  // "VUV",
  // "WST",
  // "XAF",
  // "XCD",
  // "XDR",
  // "XOF",
  // "XPF",
  // "XSU",
  // "XUA",
  // "YER",
  // "ZAR",
  // "ZMW",
  // "ZWL",
];

const shopSchema = new Schema({
  shopName: {
    type: String,
    required: true,
    unique: true,
  },
  password: String,
  displayName: { type: String, default: "" },
  logo: { type: String, default: "" },
  description: { type: String, default: "" },
  categories: { type: [Number], default: [] },
  productCategories: { type: [{ name: String }], default: [] },
  products: { type: [Schema.Types.ObjectId], default: [] },
  isHidden: { type: Boolean, default: true },
  noteToCustomers: { type: String, default: "" },
  link: { type: String, default: "" },
  currency: { type: String, enum: CURRENCY_CODES, default: "HKD" },
  discounts: { type: [{ min: Number, percentageOff: Number }], default: [] },
  minCharge: { type: Number, default: 0 },
  igNameRequired: {
    type: Boolean,
    default: false,
  },
  boolean: { type: Boolean, default: false },
  seatNumRequired: {
    type: Boolean,
    default: false,
  },
  contactNumRequired: {
    type: Boolean,
    default: false,
  },
  deliveryAddressRequired: {
    type: Boolean,
    default: false,
  },
  pickupAddressRequired: {
    type: Boolean,
    default: false,
  },
  income: {
    type: [{ month: String, income: Number, refund: Number }],
    default: [],
  },
});

const Shop = model("Shop", shopSchema);

export default Shop;
